### Fetch Users
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "query { users { _id username email provider providerId createdAt updatedAt } }"
}

### Fetch User
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "query { user(id: \"655993bfaffb63a904a64d68\") { _id username email provider providerId createdAt updatedAt } }"
}

### Fetch Tweets
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "query { tweets { _id content authorId createdAt updatedAt } }"
}

### Fetch Facebook Posts
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "query { facebookPosts { _id authorId content createdAt updatedAt } }"
}

### Fetch Instagram Posts
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "query { instagramPosts { _id authorId imageUrl caption createdAt updatedAt } }"
}

### Create New User
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { createUser(input: { username: \"newUsername\", email: \"newEmail@example.com\", provider: \"providerName\", providerId: \"providerId123\" }) { _id username email provider providerId createdAt updatedAt } }"
}

### Create New Tweet
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { createTweet(content: \"Hello World!\", authorId: \"655986faa99ed038277103a1\") { _id content authorId createdAt updatedAt } }"
}

### Create New Facebook Post
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { createFacebookPost(content: \"This is a Facebook post!\", authorId: \"656ac160cf842be61da41007\") { _id authorId content createdAt updatedAt } }"
}

### Create New Instagram Post
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { createInstagramPost(imageUrl: \"http://example.com/image.jpg\", caption: \"This is an Instagram post!\", authorId: \"655986faa99ed038277103a1\") { _id authorId imageUrl caption createdAt updatedAt } }"
}
